[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
web3 = "7ffMY6G9LXz8KArt5CS9APuJMQC547Q7sZ194SyQ1Rij"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/durvesh/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
